version: 2
jobs:
  build:
    working_directory: ~/paraparent
    docker:
      - image: circleci/node:10.15.1
      - image: mongo:3.4
    steps:
      - add_ssh_keys:
          fingerprints:
            - "88:56:fb:39:c5:a6:bc:31:6c:54:af:0b:d9:3f:e0:b8"
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6.4.1'
      - restore-cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save-cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node-modules
      - run:
          name: test
          command: npm test
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_test_results:
          path: test-results.xml